---
- name: Active Firewall.
  ufw:
    state: enabled
    policy: deny
  when: rasp_open_firewall_port

- name: Open port.
  ufw:
    rule: allow
    port: '{{ item }}'
  with_items: "{{ rasp_open_firewall_port }}"
  when: rasp_open_firewall_port

- name: Disable Firewall.
  ufw:
    state: disabled
  when: not rasp_open_firewall_port
