---
- name: Enable Camera
  become: yes
  shell: "raspi-config nonint do_camera 0"
  when: ( CAMERA == True )

- name: Disable Camera
  become: yes
  shell: "raspi-config nonint do_camera 1"
  when: ( CAMERA == False )


