---
- name: Enable I2C
  become: yes
  shell: "raspi-config nonint do_i2c 0"
  when: ( I2C == True )

- name: Disable I2C
  become: yes
  shell: "raspi-config nonint do_i2c 1"
  when: ( I2C  == False )
