---
- name: Enable OneWire
  become: yes
  shell: "raspi-config nonint do_onewire 0"
  when: ( ONEWIRE  == True )

- name: Disable OneWire
  become: yes
  shell: "raspi-config nonint do_onewire 1"
  when: ( ONEWIRE  == False )