---
- name: Enable Remote GPIO
  become: yes
  shell: "raspi-config nonint do_rgpio 0"
  when: ( RGPIO == True )

- name: Disable Remote GPIO
  become: yes
  shell: "raspi-config nonint do_rgpio 1"
  when: ( RGPIO == False )