---
- name: Get rGPIO status
  shell: "raspi-config nonint get_rgpio"
  register: rgpio_status
  changed_when: False

- name: Enable Remote GPIO
  become: yes
  shell: "raspi-config nonint do_rgpio 0"
  when: ( RGPIO == True) and (rgpio_status.stdout != '0')

- name: Disable Remote GPIO
  become: yes
  shell: "raspi-config nonint do_rgpio 1"
  when: ( RGPIO == False) and (rgpio_status.stdout != '1')