---
- name: Get rGPIO status
  command: "raspi-config nonint get_rgpio"
  register: rgpio_status
  changed_when: False

- name: Enable Remote GPIO.
  command: "raspi-config nonint do_rgpio 0"
  when: RGPIO

- name: Disable Remote GPIO.
  command: "raspi-config nonint do_rgpio 1"
  when: not RGPIO
