---
- name: Enable serial
  become: yes
  shell: "raspi-config nonint do_serial 0"
  when: ( SERIAL == True )

- name: Disable serial
  become: yes
  shell: "raspi-config nonint do_serial 1"
  when: ( SERIAL == False )