---
- name: Enable SPI
  become: yes
  shell: "raspi-config nonint do_spi 0"
  when: ( SPI  == True )

- name: Disable SPI
  become: yes
  shell: "raspi-config nonint do_spi 1"
  when: ( SPI  == False )