---
- name: Enable VNC
  become: yes
  shell: "raspi-config nonint do_vnc 0"
  when: ( VNC == True )

- name: Disable VNC
  become: yes
  shell: "raspi-config nonint do_vnc 1"
  when: ( VNC == False )